name: Helm Lint

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run chart-testing (lint)
        id: lint
        run: |
            docker run \
            -v $(pwd):/charts \
            -w /charts \
            quay.io/helmpack/chart-testing:v3.0.0-rc.1 \
            ct lint \
            --chart-dirs=helm-charts \
            --all \
            --validate-maintainers=false
